Repository modmail-dev/Modmail, pull requests merged in 2023-11, with the labels that each got.

#3306 Fix rate limit issue on raw reaction add/remove events.
  bot.py
Labels: staged

#3257 Add config to manage how long logs are stored
  bot.py
  cogs/plugins.py
  cogs/utility.py
  core/config.py
  core/config_help.json
  core/models.py
  core/thread.py
Labels: staged

#3276 Add `rename` to `registry.json`
  plugins/registry.json
Labels: plugin registry, staged

#3295 Fix bug with `?plugin update`.
  cogs/plugins.py
Labels: staged

#3307 fix: discord invite ( new server )
  cogs/utility.py
Labels: in progress

#3269 v4.1.0 Release
  .dockerignore
  .env.example
  .github/workflows/lints.yml
  CHANGELOG.md
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
  app.json
  bot.py
  cogs/modmail.py
  cogs/plugins.py
  cogs/utility.py
  core/clients.py
  core/config.py
  core/config_help.json
  core/models.py
  core/thread.py
  core/utils.py
  plugins/registry.json
  pyproject.toml
  requirements.txt
Labels: in progress
